### ISSUE TITLE
Downloading videos 

### ISSUE THREAD

**Issue by JosephChenHub** [LisaAnne/LocalizingMoments#13]
Can you provide MD5sum code for videos? I run the download py file but sometimes get stuck and I have to restart downloading after checkpoint.  Besides, If you can provide the datasets via url link on google cloud or torrents for ipv6,  it would be a gift for us!

**Comment by LisaAnne** [comment]
*sigh* - apologies that you are getting stuck with the downloads.

Here is a google drive link: https://drive.google.com/open?id=1_oyJ5rQiZboipbMl6tkhY8v0s9zDkvJc

Hopefully that helps.  FYI, I am not sure how long I will have access to my UC Berkeley drive account; this link may be inactive starting May 2019.
