### ISSUE TITLE
Missing file: "data/frame_rate_clean.p"

### ISSUE THREAD

**Issue by skaws2003** [LisaAnne/LocalizingMoments#15]
Hi,
While trying to reproduce your work, I found "**data/frame_rate_clean.p**" used in _make_average_video_dict_flow.py_ is missing. Should I use constant frame rate for it? Or, could you provide the file?

**Comment by LisaAnne** [comment]
I just pushed this -- can you see it?

**Comment by skaws2003** [comment]
Thank you for fast response. Checked it working!
