### ISSUE TITLE
Cannot download the videos

### ISSUE THREAD

**Issue by zixuwang1996** [LisaAnne/LocalizingMoments#25]
Hi Lisa,

Thanks for the very useful dataset.

When i was trying to download the data from google drive, there are around half training videos missing due to some unknown errors (seems some cannot be compressed) so I tried the script you provided - but it seems all the links are inactive on AWS. Could you please shed some lights on this? Much appreciated!

Best wishes

**Comment by LisaAnne** [comment]
Can you try downloading from here?  https://data.ciirc.cvut.cz/public/projects/LisaAnne/

Thanks!

**Comment by tommying** [comment]
> Can you try downloading from here? https://data.ciirc.cvut.cz/public/projects/LisaAnne/
> 
> Thanks!

Hi, Thanks for the greatful dataset.
But how could I download the dataset from https://data.ciirc.cvut.cz/public/projects/LisaAnne/ , any download codes here(or i need to download it one by one manually)?

**Comment by ShramanPramanick** [comment]
Hi @tommying, 

Maybe too late for your query, but I am posting a solution in case somebody may find it useful. 

I could download the videos from [https://data.ciirc.cvut.cz/public/projects/LisaAnne/]( https://data.ciirc.cvut.cz/public/projects/LisaAnne/) by scrapping the webpage to get the URLs of all videos, and then using wget to download the videos. Here is an example script to download the training videos:

```
import requests 
from bs4 import BeautifulSoup 
import os
import subprocess

def getHTMLdocument(url):
    # request for HTML document of given url
    response = requests.get(url)
    # response will be provided in JSON format
    return response.text

didemo_page_source = 'https://data.ciirc.cvut.cz/public/projects/LisaAnne/DiDeMoRelease/train_videos/'
download_location = <Root_Directory>

# Opening the html file
HTMLFile = getHTMLdocument(didemo_page_source)

# Creating a BeautifulSoup object and specifying the parser
S = BeautifulSoup(HTMLFile)
html_source = S.body.prettify()

video_urls = S.find_all('a')
video_urls = [video_url.text for video_url in video_urls][5:]

for video_url in video_urls:
    cmd = "wget {} -P {}".format(os.path.join(didemo_page_source, video_url), download_location)
    subprocess.call(cmd, shell=True)

print("All videos are done!")
```
