### ISSUE TITLE
Question about dataset and code

### ISSUE THREAD

**Issue by yuxinyan** [LisaAnne/LocalizingMoments#4]
Hello, thanks for your great work and releasing your experiment code !
I want to use your experiment result as my baseline. But i have met some problems :
1. I used your python script to download DeDiMo dataset, but too many videos have been removed from Flickr. Could you help me download the whole dataset ?
2. I found that the code you released can't be directly used to train. Could you release the train and test code ? If you could release, please tell me when :). 
Thanks a lot !

**Comment by LisaAnne** [comment]
How many videos were no longer on flickr?  There might be a download issue, because I think you should be able to get most (if not all) the videos.  

Some videos which have been removed are linked on my webpage.

**Comment by yuxinyan** [comment]
Thank you for your reply! I found that my problem is due to my network. Now i could download video data with proxy, but i found that i randomly download some videos which are incomplete. Could you provide me the MD5 code of  the whole 10464 videos ? I can use these code to check the completeness of dataset.

**Comment by LisaAnne** [comment]
Can you let me know which videos you are missing?

**Comment by yuxinyan** [comment]
Thank you for uploading your dataset to AWS! It should solve my problem !👍

**Comment by yuxinyan** [comment]
I just found that you generated HASH code . How nice you are!  Thanks again！
