### ISSUE TITLE
Can not reproduce your result by the model you provide

### ISSUE THREAD

**Issue by h-bo** [LisaAnne/LocalizingMoments#5]
Thanks for your good work.
I am trying yo run your model but get a much lower result(0.10@1, 0.4@5, 0.25iou), I guess it may result from the glove version you use(I am using glove.6b), could you tell me the version you use?

By the way, the stacked mode I use is 'overall-video_mean + local-video_mean + segment'(by experiment, it outperforms the other stacked way, but I still want to make sure the way you use...)
Thank you

**Comment by h-bo** [comment]
And the way you put the last k entries in 50, if the text is 'I love you', should the put mode as [0, 0, ..., you, love, I] or  [0, 0, ..., I, love, you]? 
thanks

**Comment by h-bo** [comment]
And, in the readme,  should the latter  be cont_data[:-t,n ] = 0 ?
![image](https://user-images.githubusercontent.com/16351543/33270063-bb8bd932-d3bd-11e7-9543-b292b2933c9a.png)
Thanks

**Comment by h-bo** [comment]
And how you preprocess the text. You know, there are words like "someone's, baby's", they can not be encoded but meaningful in fact. Thanks!

**Comment by mengliu1991** [comment]
@h-bo you run the code that the author provided or you realize the code by yourself?

**Comment by h-bo** [comment]
@mengliu1991 the author provided

**Comment by mengliu1991** [comment]
@h-bo can you tell me how you set the input data for the code that the author provided? I am not sure about the loc_data, it is the location of the ground truth moment or the time of the currently input video clip?
And the loss function in the author's code is different from the one in her paper? Do you change it ?

Thank you.

**Comment by h-bo** [comment]
I do not get the result she provides, you must know. @mengliu1991
